apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  ports:
    - ports: 6379
      targetPort: 6379
  selector:
    name: result-app-pod
    app: demo-voting-app